version: "3"
services:
  python-masscan:
    image: xosh/python-masscanner
    build: .
    volumes:
      - ./settings.json:/python-masscan/settings.json:ro
      - ./proxyscan.log:/python-masscan/proxyscan.log:rw
      - ./open_proxy.txt:/python-masscan/open_proxy.txt:rw
    network_mode: host
    restart: on-failure
