version: "3.2"
services:
  mariadb:
    image: mariadb
    container_name: python-masscan-database
    restart: on-failure
    volumes:
      - mariadb-volume:/var/lib/mysql:rw
      - ./mariadb.sql:/docker-entrypoint-initdb.d/01_mariadb.sql:ro
    environment:
      - MYSQL_HOST="%"
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    networks:
      - backend
  python-masscan:
    image: "xosh/python-masscan-backend"
    restart: on-failure
    container_name: python-masscan-backend
    ports:
      - "8888:8888"
    networks:
      - backend
    links:
      - mariadb

networks:
  backend:

volumes:
  mariadb-volume:
