version: "3"
services:
  mariadb:
    image: mariadb
    restart: on-failure
    env_file:
      - .env.docker
    volumes:
      - python-masscan-mariadb-volume:/var/lib/mysql:rw
      - ./mariadb.sql:/docker-entrypoint-initdb.d/01_mariadb.sql:ro
    networks:
      - python-masscan-backend
  python-masscan:
    build: .
    env_file:
      - .env.docker
    image: xosh/python-masscan-backend
    restart: on-failure
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - python-masscan-backend
    links:
      - mariadb

networks:
  python-masscan-backend:

volumes:
  python-masscan-mariadb-volume:
