version: "3"
services:
  mariadb:
    image: python-masscan-mariadb
    restart: on-failure
    env_file:
      - .env.docker
    volumes:
      - python-masscan-mariadb-volume:/var/lib/mysql:rw
      - ./mariadb.sql:/docker-entrypoint-initdb.d/01_mariadb.sql:ro
    environment:
      - MYSQL_HOST="%"
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    networks:
      - python-masscan-backend
  python-masscan:
    build: .
    env_file:
      - .env.docker
    image: xosh/python-masscan-backend
    restart: on-failure
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - python-masscan-backend
    links:
      - python-masscan-mariadb

networks:
  python-masscan-backend:

volumes:
  python-masscan-mariadb-volume:
